#pragma once

#include <ostream>
#include <string>

#include "App.h"
#include "Commander.h"
#include "Config.h"

namespace drea::core::integrations::Fish {

// Escape for fish single-quoted strings: ' and \ only.
static std::string escape( std::string_view s )
{
	std::string	res;
	res.reserve( s.size() );
	for( char c: s ){
		if( c == '\'' || c == '\\' ){
			res += '\\';
		}
		res += c;
	}
	return res;
}

// Build a seen-subcommands predicate like __fish_seen_subcommand_from a b c
static std::string seenPredicate( const std::string & path )
{
	std::string		res = "__fish_seen_subcommand_from";
	std::string		word;
	for( char c: path ){
		if( c == '.' ){
			if( !word.empty() ){
				res += ' ';
				res += word;
				word.clear();
			}
		}else{
			word += c;
		}
	}
	if( !word.empty() ){
		res += ' ';
		res += word;
	}
	return res;
}

static void generateAutoCompletion( const drea::core::App & app, std::ostream & out )
{
	const std::string	name = app.name();

	out << "# fish completion for " << name << " (generated by drea)\n\n";

	// Collect top-level command names for the "no subcommand yet" predicate.
	std::string		topList;
	app.commander().commands( [&topList]( const Command & cmd ){
		if( cmd.mHidden || !cmd.mParentCommand.empty() ){
			return;
		}
		if( !topList.empty() ){
			topList += ' ';
		}
		topList += cmd.mName;
	});

	// Top-level commands
	app.commander().commands( [&out, &name, &topList]( const Command & cmd ){
		if( cmd.mHidden || !cmd.mParentCommand.empty() ){
			return;
		}
		out << "complete -c " << name
		    << " -n \"not __fish_seen_subcommand_from " << topList << "\""
		    << " -f -a '" << escape( cmd.mName ) << "'"
		    << " -d '" << escape( cmd.mDescription ) << "'\n";
	});

	// Subcommands
	app.commander().commands( [&out, &name]( const Command & cmd ){
		if( cmd.mHidden || cmd.mParentCommand.empty() ){
			return;
		}
		std::string	parentPath = cmd.mParentCommand;
		out << "complete -c " << name
		    << " -n \"" << seenPredicate( parentPath ) << "\""
		    << " -f -a '" << escape( cmd.mName ) << "'"
		    << " -d '" << escape( cmd.mDescription ) << "'\n";
	});

	// Per-command options
	app.commander().commands( [&out, &name, &app]( const Command & cmd ){
		if( cmd.mHidden ){
			return;
		}
		std::string		fullPath = cmd.mParentCommand.empty() ? cmd.mName : cmd.mParentCommand + "." + cmd.mName;
		std::string		predicate = seenPredicate( fullPath );
		auto emit = [&out, &name, &predicate, &app]( const std::string & optName ){
			auto opt = app.config().find( optName );
			if( !opt ){
				return;
			}
			out << "complete -c " << name
			    << " -n \"" << predicate << "\""
			    << " -l " << opt->mName;
			if( !opt->mShortVersion.empty() ){
				out << " -s " << opt->mShortVersion;
			}
			if( !opt->mParamName.empty() ){
				out << " -r";
			}
			out << " -d '" << escape( opt->mDescription ) << "'\n";
		};
		for( const auto & o: cmd.mLocalParameters ){
			emit( o );
		}
		for( const auto & o: cmd.mGlobalParameters ){
			emit( o );
		}
	});
}

}
