#pragma once

#include <ostream>
#include <string>

#include "App.h"
#include "Commander.h"
#include "Config.h"
#include "utilities/string.h"

namespace drea::core::integrations::Zsh {

// Escape single quotes for zsh single-quoted strings: ' -> '\''
inline std::string escape( std::string_view s )
{
	std::string	res;
	res.reserve( s.size() );
	for( char c: s ){
		if( c == '\'' ){
			res += "'\\''";
		}else{
			res += c;
		}
	}
	return res;
}

inline void generateAutoCompletion( const drea::core::App & app, std::ostream & out )
{
	const std::string	name = app.name();

	out << "#compdef " << name << "\n";
	out << "# zsh completion for " << name << " (generated by drea)\n\n";

	// Per-command option descriptor function. Lists local + global options.
	out << "_" << name << "_opts_for() {\n";
	out << "    local cmd=\"$1\"\n";
	out << "    case \"$cmd\" in\n";
	app.commander().commands( [&out, &app]( const Command & cmd ){
		if( !app.commander().isVisible( cmd ) ){
			return;
		}
		std::string path = cmd.mParentCommand.empty() ? cmd.mName : cmd.mParentCommand + "." + cmd.mName;
		// zsh uses spaces between subcommands
		std::string display = path;
		for( auto & ch: display ){
			if( ch == '.' ){
				ch = ' ';
			}
		}
		out << "        '" << escape( display ) << "')\n";
		out << "            _arguments";
		if( !cmd.mParamChoices.empty() ){
			std::string	action = "(";
			for( const auto & choice: cmd.mParamChoices ){
				if( action.size() > 1 ){
					action += ' ';
				}
				action += choice;
			}
			action += ")";
			out << " \\\n                '1: :" << escape( action ) << "'";
		}
		auto emitOption = [&out, &app]( const std::string & optName ){
			auto opt = app.config().find( optName );
			if( !opt ){
				return;
			}
			// options with choices complete their values: the action is the
			// literal word list, e.g. (none readonly operator)
			std::string	action;
			if( !opt->mChoices.empty() ){
				action = "(";
				for( const auto & choice: opt->mChoices ){
					if( action.size() > 1 ){
						action += ' ';
					}
					action += choice;
				}
				action += ")";
			}
			out << " \\\n                '--" << escape( opt->mName );
			if( !opt->mParamName.empty() ){
				out << "=[" << escape( opt->mDescription ) << "]:" << escape( opt->mParamName ) << ":" << escape( action );
			}else{
				out << "[" << escape( opt->mDescription ) << "]";
			}
			out << "'";
			if( !opt->mShortVersion.empty() ){
				out << " \\\n                '-" << escape( opt->mShortVersion );
				if( !opt->mParamName.empty() ){
					out << "[" << escape( opt->mDescription ) << "]:" << escape( opt->mParamName ) << ":" << escape( action );
				}else{
					out << "[" << escape( opt->mDescription ) << "]";
				}
				out << "'";
			}
		};
		for( const auto & o: cmd.mLocalParameters ){
			emitOption( o );
		}
		for( const auto & o: cmd.mGlobalParameters ){
			emitOption( o );
		}
		out << "\n            ;;\n";
	});
	out << "    esac\n";
	out << "}\n\n";

	// Main dispatcher
	out << "_" << name << "() {\n";
	out << "    local -a _top_commands\n";
	out << "    _top_commands=(\n";
	app.commander().commands( [&app, &out]( const Command & cmd ){
		if( !app.commander().isVisible( cmd ) || !cmd.mParentCommand.empty() ){
			return;
		}
		out << "        '" << escape( cmd.mName ) << ":" << escape( utilities::string::firstLine( cmd.mDescription ) ) << "'\n";
	});
	out << "    )\n";

	out << "    local context state line\n";
	out << "    typeset -A opt_args\n";
	out << "    _arguments -C \\\n";
	out << "        '1: :->cmd' \\\n";
	out << "        '*::arg:->args'\n";
	out << "    case $state in\n";
	out << "        cmd)\n";
	out << "            _describe -t commands '" << escape( name ) << " command' _top_commands\n";
	out << "            ;;\n";
	out << "        args)\n";
	out << "            local path=\"${words[1]}\"\n";
	out << "            local depth=2\n";
	out << "            # Walk subcommands to build a space-separated path\n";
	out << "            while (( depth <= ${#words} )); do\n";
	out << "                local candidate=\"${path} ${words[$depth]}\"\n";
	out << "                local matched=0\n";
	app.commander().commands( [&app, &out]( const Command & cmd ){
		if( !app.commander().isVisible( cmd ) || cmd.mParentCommand.empty() ){
			return;
		}
		std::string display = cmd.mParentCommand + "." + cmd.mName;
		for( auto & ch: display ){
			if( ch == '.' ){
				ch = ' ';
			}
		}
		out << "                [[ \"$candidate\" == '" << escape( display ) << "' ]] && matched=1\n";
	});
	out << "                (( matched )) || break\n";
	out << "                path=\"$candidate\"\n";
	out << "                (( depth++ ))\n";
	out << "            done\n";
	out << "            _" << name << "_opts_for \"$path\"\n";
	out << "            ;;\n";
	out << "    esac\n";
	out << "}\n\n";
	out << "_" << name << " \"$@\"\n";
}

}
