#pragma once

#include <ostream>
#include <set>
#include <string>
#include <vector>
#include <ctime>

#include <spdlog/fmt/fmt.h>

#include "App.h"
#include "Commander.h"
#include "Config.h"
#include "utilities/string.h"

namespace drea::core::integrations::Man {

// Escape a string for inclusion in a groff man page.
// - leading dots become zero-width + dot so they are not treated as commands
// - backslashes are doubled
inline std::string escape( std::string_view s )
{
	std::string	res;
	res.reserve( s.size() );
	for( size_t i = 0; i < s.size(); ++i ){
		const char c = s[i];
		if( c == '\\' ){
			res += "\\\\";
		}else if( c == '-' ){
			res += "\\-";
		}else{
			res += c;
		}
	}
	return res;
}

// Escape but also guard a leading dot on a fresh line.
inline std::string escapeBody( std::string_view s )
{
	std::string		res;
	bool			atLineStart = true;
	for( char c: s ){
		if( atLineStart && c == '.' ){
			res += "\\&";
		}
		if( c == '\\' ){
			res += "\\\\";
		}else{
			res += c;
		}
		atLineStart = ( c == '\n' );
	}
	return res;
}

/*! The EXAMPLES section: worked invocations, one per line, unfilled so that a
	command line is not reflowed. Examples are shown by --help and by describe;
	the man page is built from the same metadata.
*/
inline void writeExamplesSection( std::ostream & out, const std::vector<std::string> & examples )
{
	if( examples.empty() ){
		return;
	}
	out << ".SH EXAMPLES\n";
	out << ".RS\n";
	out << ".nf\n";
	for( const std::string & example: examples ){
		// escape() also turns hyphens into \- so that flags stay copy
		// pasteable; a leading "." or "'" would be read as a roff request, so
		// it gets the zero width guard
		if( !example.empty() && ( example.front() == '.' || example.front() == '\'' ) ){
			out << "\\&";
		}
		out << escape( example ) << "\n";
	}
	out << ".fi\n";
	out << ".RE\n";
}

inline std::string today()
{
	std::time_t 	t = std::time( nullptr );
	std::tm			tm{};
#ifdef _WIN32
	gmtime_s( &tm, &t );
#else
	gmtime_r( &t, &tm );
#endif
	char buf[16];
	std::strftime( buf, sizeof( buf ), "%Y-%m-%d", &tm );
	return std::string( buf );
}

// The computed facts help also renders: choices, declared default, required.
// Deprecation is appended to the description by the caller.
inline std::string optionFacts( const drea::core::App & app, const drea::core::Option & opt )
{
	std::string	res;

	if( !opt.mChoices.empty() ){
		res += "One of: " + utilities::string::join( opt.mChoices, ", " ) + ". ";
	}
	if( const auto defaults = app.config().declaredDefault( opt.mName ); !defaults.empty() ){
		if( opt.mSensitive ){
			res += "Default (hidden). ";
		}else{
			res += "Default";
			for( const auto & value: defaults ){
				res += " " + opt.toString( value );
			}
			res += ". ";
		}
	}
	if( opt.mRequired ){
		res += "Required. ";
	}
	if( !res.empty() ){
		res.pop_back();
	}
	return res;
}

inline void writeOption( const drea::core::App & app, std::ostream & out, const drea::core::Option & opt )
{
	out << ".TP\n";
	out << "\\fB";
	if( !opt.mShortVersion.empty() ){
		out << "\\-" << escape( opt.mShortVersion ) << "\\fR, \\fB";
	}
	out << "\\-\\-" << escape( opt.mName ) << "\\fR";
	if( !opt.mParamName.empty() ){
		out << " \\fI" << escape( opt.mParamName ) << "\\fR";
	}
	out << "\n";
	if( !opt.mDescription.empty() ){
		out << escapeBody( opt.mDescription );
		if( opt.mDeprecated ){
			out << " (deprecated)";
		}
		out << "\n";
	}
	if( const std::string facts = optionFacts( app, opt ); !facts.empty() ){
		out << ".br\n" << escapeBody( facts ) << "\n";
	}
}

inline void writeOptionsSection( const drea::core::App & app, std::ostream & out,
                                 const std::vector<std::string> & local,
                                 const std::vector<std::string> & global )
{
	auto emit = [&out, &app]( const std::string & optName ){
		if( auto opt = app.config().find( optName ) ){
			writeOption( app, out, *opt );
		}
	};
	if( !local.empty() ){
		out << ".SH OPTIONS\n";
		for( const auto & o: local ){
			emit( o );
		}
	}
	if( !global.empty() ){
		out << ".SH GLOBAL OPTIONS\n";
		for( const auto & o: global ){
			emit( o );
		}
	}
}

// Top-level man page (section 1).
inline void generateManPage( const drea::core::App & app, std::ostream & out )
{
	const std::string	name = app.name();
	const std::string	upper = [ &name ]{
		std::string s = name;
		for( auto & c: s ){
			c = static_cast<char>( std::toupper( static_cast<unsigned char>( c ) ) );
		}
		return s;
	}();

	out << ".\\\" Man page for " << name << " (generated by drea)\n";
	out << ".TH " << upper << " 1 \"" << today() << "\" \""
	    << escape( name ) << " " << escape( app.version() ) << "\" \"User Commands\"\n";

	out << ".SH NAME\n";
	out << escape( name );
	if( !app.description().empty() ){
		// NAME is a one liner: the full text goes to DESCRIPTION
		out << " \\- " << escapeBody( utilities::string::firstLine( app.description() ) );
	}
	out << "\n";

	out << ".SH SYNOPSIS\n";
	if( auto root = app.commander().root() ){
		out << ".B " << escape( name ) << "\n";
		out << "[\\fIOPTIONS\\fR]";
		for( const auto & param: utilities::string::split( root->mParamName, " " ) ){
			out << " \\fI" << escape( param ) << "\\fR";
		}
		if( root->mNbParams == drea::core::Command::mUnlimitedParams ){
			out << "...";
		}
		out << "\n";
		if( !app.commander().empty() ){
			out << ".br\n";
			out << ".B " << escape( name ) << "\n";
			out << "[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]\n";
		}
	}else{
		out << ".B " << escape( name ) << "\n";
		if( !app.commander().empty() ){
			out << "[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]\n";
		}else{
			out << "[\\fIOPTIONS\\fR]\n";
		}
	}

	{
		// the app description, plus what the root params do when the app takes
		// arguments of its own
		auto 		root = app.commander().root();
		std::string	description = app.description();

		if( root && !root->mDescription.empty() ){
			if( !description.empty() && description.back() != '\n' ){
				description += "\n";
			}
			description += root->mDescription;
		}
		if( !description.empty() ){
			out << ".SH DESCRIPTION\n";
			out << escapeBody( description ) << "\n";
		}
	}

	// Global options: all options not used as local-only. Mirrors help.h logic.
	std::set<std::string>	localOnly;
	{
		std::set<std::string>	allLocal;
		std::set<std::string>	allGlobal;

		app.commander().commands( [ &allLocal, &allGlobal ]( const Command & cmd ){
			for( const auto & o: cmd.mLocalParameters ){
				allLocal.insert( o );
			}
			for( const auto & o: cmd.mGlobalParameters ){
				allGlobal.insert( o );
			}
		});
		for( const auto & o: allLocal ){
			if( !allGlobal.count( o ) ){
				localOnly.insert( o );
			}
		}
	}

	bool anyLine = false;
	app.config().options( [ &anyLine, &localOnly ]( const Option & o ){
		if( o.helpInLine() && !localOnly.count( o.mName ) ){
			anyLine = true;
		}
	});
	if( anyLine ){
		out << ".SH OPTIONS\n";
		app.config().options( [ &app, &out, &localOnly ]( const Option & opt ){
			if( !opt.helpInLine() || localOnly.count( opt.mName ) ){
				return;
			}
			writeOption( app, out, opt );
		});
	}

	if( !app.commander().empty() ){
		out << ".SH COMMANDS\n";
		app.commander().commands( [ &app, &out ]( const Command & cmd ){
			if( !app.commander().isVisible( cmd ) || !cmd.mParentCommand.empty() ){
				return;
			}
			out << ".TP\n";
			out << "\\fB" << escape( cmd.mName ) << "\\fR";
			if( !cmd.mSubcommand.empty() ){
				out << " \\fICOMMAND\\fR";
			}
			out << "\n";
			if( !cmd.mDescription.empty() ){
				out << escapeBody( cmd.mDescription ) << "\n";
			}
		});

		// Subcommands
		bool anySub = false;
		app.commander().commands( [ &app, &anySub ]( const Command & cmd ){
			if( app.commander().isVisible( cmd ) && !cmd.mParentCommand.empty() ){
				anySub = true;
			}
		});
		if( anySub ){
			out << ".SH SUBCOMMANDS\n";
			app.commander().commands( [ &app, &out ]( const Command & cmd ){
				if( !app.commander().isVisible( cmd ) || cmd.mParentCommand.empty() ){
					return;
				}
				std::string path = cmd.mParentCommand + "." + cmd.mName;
				out << ".TP\n";
				out << "\\fB" << escape( utilities::string::replace( path, ".", " " ) ) << "\\fR\n";
				if( !cmd.mDescription.empty() ){
					out << escapeBody( cmd.mDescription ) << "\n";
				}
			});
		}
	}

	{
		// the app's own examples: the root params, when declared
		std::vector<std::string>	examples;

		if( auto root = app.commander().root() ){
			examples = root->mExamples;
		}
		writeExamplesSection( out, examples );
	}

	out << ".SH ENVIRONMENT\n";
	out << "Configuration options may be set through environment variables when an env prefix has been configured for this application. See the project documentation for details.\n";

	out << ".SH AUTHOR\n";
	out << "Generated by drea.\n";
}

// Per-command man page (section 1). Falls back to top-level if commandName is empty
// or unknown.
inline void generateManPage( const drea::core::App & app, std::string_view commandName, std::ostream & out )
{
	if( commandName.empty() ){
		generateManPage( app, out );
		return;
	}
	auto cmd = app.commander().find( commandName );
	if( !cmd || !app.commander().isVisible( *cmd ) ){
		generateManPage( app, out );
		return;
	}

	const std::string	appName = app.name();
	const std::string	flatName = utilities::string::replace( std::string( commandName ), ".", "-" );
	const std::string	pageName = appName + "-" + flatName;
	std::string			upper = pageName;
	for( auto & c: upper ){
		c = static_cast<char>( std::toupper( static_cast<unsigned char>( c ) ) );
	}

	out << ".\\\" Man page for " << pageName << " (generated by drea)\n";
	out << ".TH " << escape( upper ) << " 1 \"" << today() << "\" \""
	    << escape( appName ) << " " << escape( app.version() ) << "\" \"User Commands\"\n";

	out << ".SH NAME\n";
	out << escape( pageName );
	if( !cmd->mDescription.empty() ){
		// NAME is a one liner: the full text goes to DESCRIPTION
		out << " \\- " << escapeBody( utilities::string::firstLine( cmd->mDescription ) );
	}
	out << "\n";

	auto pathParts = utilities::string::split( commandName, "." );
	out << ".SH SYNOPSIS\n";
	out << ".B " << escape( appName ) << " " << escape( utilities::string::join( pathParts, " " ) ) << "\n";
	{
		// no trailing space: mandoc reports one as a style problem
		std::vector<std::string>	parts;

		if( !cmd->mSubcommand.empty() ){
			parts.emplace_back( "\\fICOMMAND\\fR" );
		}
		if( cmd->numberOfParams() > 0 || cmd->numberOfParams() == drea::core::Command::mUnlimitedParams ){
			parts.push_back( fmt::format( "\\fI{}\\fR", escape( cmd->nameOfParamsForHelp() ) ) );
		}
		if( !cmd->mLocalParameters.empty() || !cmd->mGlobalParameters.empty() ){
			parts.emplace_back( "[\\fIOPTIONS\\fR]" );
		}
		out << utilities::string::join( parts, " " ) << "\n";
	}

	if( !cmd->mDescription.empty() ){
		out << ".SH DESCRIPTION\n";
		out << escapeBody( cmd->mDescription ) << "\n";
	}

	if( !cmd->mParamChoices.empty() ){
		out << ".SH ARGUMENTS\n";
		out << ".TP\n";
		out << "\\fI" << escape( cmd->mParamName ) << "\\fR\n";
		out << "One of: " << escapeBody( utilities::string::join( cmd->mParamChoices, ", " ) ) << "\n";
	}

	if( !cmd->mSubcommand.empty() ){
		out << ".SH COMMANDS\n";
		for( const auto & subName: cmd->mSubcommand ){
			auto sub = app.commander().find( std::string( commandName ) + "." + subName );
			if( !sub || !app.commander().isVisible( *sub ) ){
				continue;
			}
			out << ".TP\n";
			out << "\\fB" << escape( sub->mName ) << "\\fR\n";
			if( !sub->mDescription.empty() ){
				out << escapeBody( sub->mDescription ) << "\n";
			}
		}
	}

	writeOptionsSection( app, out, cmd->mLocalParameters, cmd->mGlobalParameters );

	writeExamplesSection( out, cmd->mExamples );

	out << ".SH SEE ALSO\n";
	out << ".BR " << escape( appName ) << " (1)\n";
}

}
