#pragma once

#include <ostream>
#include <set>
#include <string>
#include <ctime>

#include "App.h"
#include "Commander.h"
#include "Config.h"
#include "utilities/string.h"

namespace drea::core::integrations::Man {

// Escape a string for inclusion in a groff man page.
// - leading dots become zero-width + dot so they are not treated as commands
// - backslashes are doubled
static std::string escape( std::string_view s )
{
	std::string	res;
	res.reserve( s.size() );
	for( size_t i = 0; i < s.size(); ++i ){
		const char c = s[i];
		if( c == '\\' ){
			res += "\\\\";
		}else if( c == '-' ){
			res += "\\-";
		}else{
			res += c;
		}
	}
	return res;
}

// Escape but also guard a leading dot on a fresh line.
static std::string escapeBody( std::string_view s )
{
	std::string		res;
	bool			atLineStart = true;
	for( char c: s ){
		if( atLineStart && c == '.' ){
			res += "\\&";
		}
		if( c == '\\' ){
			res += "\\\\";
		}else{
			res += c;
		}
		atLineStart = ( c == '\n' );
	}
	return res;
}

static std::string today()
{
	std::time_t 	t = std::time( nullptr );
	std::tm			tm{};
#ifdef _WIN32
	gmtime_s( &tm, &t );
#else
	gmtime_r( &t, &tm );
#endif
	char buf[16];
	std::strftime( buf, sizeof( buf ), "%Y-%m-%d", &tm );
	return std::string( buf );
}

static void writeOptionsSection( const drea::core::App & app, std::ostream & out,
                                 const std::vector<std::string> & local,
                                 const std::vector<std::string> & global )
{
	auto emit = [&out, &app]( const std::string & optName ){
		auto opt = app.config().find( optName );
		if( !opt ){
			return;
		}
		out << ".TP\n";
		out << "\\fB";
		if( !opt->mShortVersion.empty() ){
			out << "\\-" << escape( opt->mShortVersion ) << "\\fR, \\fB";
		}
		out << "\\-\\-" << escape( opt->mName ) << "\\fR";
		if( !opt->mParamName.empty() ){
			out << " \\fI" << escape( opt->mParamName ) << "\\fR";
		}
		out << "\n";
		if( !opt->mDescription.empty() ){
			out << escapeBody( opt->mDescription ) << "\n";
		}
	};
	if( !local.empty() ){
		out << ".SH OPTIONS\n";
		for( const auto & o: local ){
			emit( o );
		}
	}
	if( !global.empty() ){
		out << ".SH GLOBAL OPTIONS\n";
		for( const auto & o: global ){
			emit( o );
		}
	}
}

// Top-level man page (section 1).
static void generateManPage( const drea::core::App & app, std::ostream & out )
{
	const std::string	name = app.name();
	const std::string	upper = [ &name ]{
		std::string s = name;
		for( auto & c: s ){
			c = static_cast<char>( std::toupper( static_cast<unsigned char>( c ) ) );
		}
		return s;
	}();

	out << ".\\\" Man page for " << name << " (generated by drea)\n";
	out << ".TH " << upper << " 1 \"" << today() << "\" \""
	    << escape( name ) << " " << escape( app.version() ) << "\" \"User Commands\"\n";

	out << ".SH NAME\n";
	out << escape( name );
	if( !app.description().empty() ){
		out << " \\- " << escapeBody( app.description() );
	}
	out << "\n";

	out << ".SH SYNOPSIS\n";
	out << ".B " << escape( name ) << "\n";
	if( !app.commander().empty() ){
		out << "[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]\n";
	}else{
		out << "[\\fIOPTIONS\\fR]\n";
	}

	if( !app.description().empty() ){
		out << ".SH DESCRIPTION\n";
		out << escapeBody( app.description() ) << "\n";
	}

	// Global options: all options not used as local-only. Mirrors help.h logic.
	std::set<std::string>	localOnly;
	{
		std::set<std::string>	allLocal;
		std::set<std::string>	allGlobal;

		app.commander().commands( [ &allLocal, &allGlobal ]( const Command & cmd ){
			for( const auto & o: cmd.mLocalParameters ){
				allLocal.insert( o );
			}
			for( const auto & o: cmd.mGlobalParameters ){
				allGlobal.insert( o );
			}
		});
		for( const auto & o: allLocal ){
			if( !allGlobal.count( o ) ){
				localOnly.insert( o );
			}
		}
	}

	bool anyLine = false;
	app.config().options( [ &anyLine, &localOnly ]( const Option & o ){
		if( o.helpInLine() && !localOnly.count( o.mName ) ){
			anyLine = true;
		}
	});
	if( anyLine ){
		out << ".SH OPTIONS\n";
		app.config().options( [ &out, &localOnly ]( const Option & opt ){
			if( !opt.helpInLine() || localOnly.count( opt.mName ) ){
				return;
			}
			out << ".TP\n";
			out << "\\fB";
			if( !opt.mShortVersion.empty() ){
				out << "\\-" << escape( opt.mShortVersion ) << "\\fR, \\fB";
			}
			out << "\\-\\-" << escape( opt.mName ) << "\\fR";
			if( !opt.mParamName.empty() ){
				out << " \\fI" << escape( opt.mParamName ) << "\\fR";
			}
			out << "\n";
			if( !opt.mDescription.empty() ){
				out << escapeBody( opt.mDescription ) << "\n";
			}
		});
	}

	if( !app.commander().empty() ){
		out << ".SH COMMANDS\n";
		app.commander().commands( [ &out ]( const Command & cmd ){
			if( cmd.mHidden || !cmd.mParentCommand.empty() ){
				return;
			}
			out << ".TP\n";
			out << "\\fB" << escape( cmd.mName ) << "\\fR";
			if( !cmd.mSubcommand.empty() ){
				out << " \\fICOMMAND\\fR";
			}
			out << "\n";
			if( !cmd.mDescription.empty() ){
				out << escapeBody( cmd.mDescription ) << "\n";
			}
		});

		// Subcommands
		bool anySub = false;
		app.commander().commands( [ &anySub ]( const Command & cmd ){
			if( !cmd.mHidden && !cmd.mParentCommand.empty() ){
				anySub = true;
			}
		});
		if( anySub ){
			out << ".SH SUBCOMMANDS\n";
			app.commander().commands( [ &out ]( const Command & cmd ){
				if( cmd.mHidden || cmd.mParentCommand.empty() ){
					return;
				}
				std::string path = cmd.mParentCommand + "." + cmd.mName;
				out << ".TP\n";
				out << "\\fB" << escape( utilities::string::replace( path, ".", " " ) ) << "\\fR\n";
				if( !cmd.mDescription.empty() ){
					out << escapeBody( cmd.mDescription ) << "\n";
				}
			});
		}
	}

	out << ".SH ENVIRONMENT\n";
	out << "Configuration options may be set through environment variables when an env prefix has been configured for this application. See the project documentation for details.\n";

	out << ".SH AUTHOR\n";
	out << "Generated by drea.\n";
}

// Per-command man page (section 1). Falls back to top-level if commandName is empty
// or unknown.
static void generateManPage( const drea::core::App & app, std::string_view commandName, std::ostream & out )
{
	if( commandName.empty() ){
		generateManPage( app, out );
		return;
	}
	auto cmd = app.commander().find( commandName );
	if( !cmd ){
		generateManPage( app, out );
		return;
	}

	const std::string	appName = app.name();
	const std::string	flatName = utilities::string::replace( std::string( commandName ), ".", "-" );
	const std::string	pageName = appName + "-" + flatName;
	std::string			upper = pageName;
	for( auto & c: upper ){
		c = static_cast<char>( std::toupper( static_cast<unsigned char>( c ) ) );
	}

	out << ".\\\" Man page for " << pageName << " (generated by drea)\n";
	out << ".TH " << escape( upper ) << " 1 \"" << today() << "\" \""
	    << escape( appName ) << " " << escape( app.version() ) << "\" \"User Commands\"\n";

	out << ".SH NAME\n";
	out << escape( pageName );
	if( !cmd->mDescription.empty() ){
		out << " \\- " << escapeBody( cmd->mDescription );
	}
	out << "\n";

	auto pathParts = utilities::string::split( commandName, "." );
	out << ".SH SYNOPSIS\n";
	out << ".B " << escape( appName ) << " " << escape( utilities::string::join( pathParts, " " ) ) << "\n";
	if( !cmd->mSubcommand.empty() ){
		out << "\\fICOMMAND\\fR ";
	}
	if( cmd->numberOfParams() > 0 || cmd->numberOfParams() == drea::core::Command::mUnlimitedParams ){
		out << "\\fI" << escape( cmd->nameOfParamsForHelp() ) << "\\fR ";
	}
	if( !cmd->mLocalParameters.empty() || !cmd->mGlobalParameters.empty() ){
		out << "[\\fIOPTIONS\\fR]";
	}
	out << "\n";

	if( !cmd->mDescription.empty() ){
		out << ".SH DESCRIPTION\n";
		out << escapeBody( cmd->mDescription ) << "\n";
	}

	if( !cmd->mSubcommand.empty() ){
		out << ".SH COMMANDS\n";
		for( const auto & subName: cmd->mSubcommand ){
			auto sub = app.commander().find( std::string( commandName ) + "." + subName );
			if( !sub || sub->mHidden ){
				continue;
			}
			out << ".TP\n";
			out << "\\fB" << escape( sub->mName ) << "\\fR\n";
			if( !sub->mDescription.empty() ){
				out << escapeBody( sub->mDescription ) << "\n";
			}
		}
	}

	writeOptionsSection( app, out, cmd->mLocalParameters, cmd->mGlobalParameters );

	out << ".SH SEE ALSO\n";
	out << ".BR " << escape( appName ) << " (1)\n";
}

}
